### ISSUE TITLE
Electron 4 Win64 Support

### ISSUE THREAD

**Issue by Djiit** [wilix-team/iohook#151]
## Expected Behavior

v0.4.0 Should work with Electron on Windows x64.

## Current Behavior

While macOS and Ubuntu are fine, I can't use the newest version on my Windows machine. I get a "Module did not self-register" error when starting the app.

## Steps to Reproduce (for bugs)

1. Use electron-example in this repo.
2. Change Electron version to ^4.0.4
3. Run `yarn start`

## Your Environment

* Version used: v0.4.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): electron 4.0.8
* Operating System and version (desktop or mobile): Windows 10 

Is this related to my system only ? @anoadragon453 did you see anything like that ?

**Comment by anoadragon453** [comment]
Haven't tested Windows myself yet (can do on Monday), but @kolnogorov seemed to find success.

**Comment by kolnogorov** [comment]
Yes, I've managed to build it under Mac, but i have no Windows machine, so i tried to build iohook under Virtual Machine on Windows, but haven't succeeded due to lack of Visual Studio and other libraries I've tried to install but still couldn't compile.

**Comment by Djiit** [comment]
@kolnogorov : It might be related to you PATH (i.e. Windows not knowing where to find VS).

I was able to compile it on Windows, but unable to use it in a Electron 4 env (NodeJS 11 is ok).

**Comment by kolnogorov** [comment]
@Djiit i thought i added everything related to VS in PATH, but to insure, could you please tell what should i have installed and added to PATH to compile it? Because, on mac it compiles out of the box, but I have not many experience with Windows.

Thanks in advance!

**Comment by Djiit** [comment]
I don't know either, you can check this great list : https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules.

But AppVeyor successfully builds it so you should be able to pull prebuilt binaries when you run `yarn add iohook`(i.e. no need to build it).

**Comment by anoadragon453** [comment]
@kolnogorov Make sure you've installed resources for VS C++ 2017, as that's what we're using now.

**Comment by staticbass** [comment]
I get `Error: The specified module could not be found` in `...\resources\app.asar...\iohook.node`, but mac application works fine.

env: Parallels Windows 10 x64
electron: 4.0.8
iohook: 0.4.0

**Comment by anoadragon453** [comment]
> I get Error: The specified module could not be found in ...\resources\app.asar...\iohook.node , but mac application works fine.

Does this file exist?

**Comment by Djiit** [comment]
(FWIW, this file is present on my machine. Just corrupted or unusable in some way)

**Comment by staticbass** [comment]
@anoadragon453 Yes, it does. The full path - `\resources\app.asar.unpacked\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node`

**Comment by karacas** [comment]
Here:
iohook: Error: The specified procedure could not be found.
\\?\c:\test\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node
(the file exist)

**Comment by GeometricAlgorithm** [comment]
I am getting the same windows error, @karacas .

Please advise if you have found a solution.

**Comment by Japangeek** [comment]
I can confirm, I'm getting the same error by "iohook: Error: The specified procedure could not be found." even if the iohook.node exists.
I'm using iohook v0.4.0 and electron 4.0.0 too. (Windows here)

**Comment by jryans** [comment]
Since you are use `cmake-js` here instead of `node-gyp`, I think you may need a version of `cmake-js` with [this PR](https://github.com/cmake-js/cmake-js/pull/165) merged.

Consider forking `cmake-js` maybe?

**Comment by anoadragon453** [comment]
If people could try with this PR branch and report back if it works that would be most appreciated https://github.com/wilix-team/iohook/pull/157

**Comment by BloodyIron** [comment]
Hoping to get this sorted to roll out an upstream feature!

**Comment by Djiit** [comment]
Closed by https://github.com/wilix-team/iohook/pull/159

**Comment by Suhail** [comment]
Hi I am trying to make this work with Electron 4.2.2 but I get this error:
```
Uncaught Error: Cannot find module 'C:\Users\digit\Desktop\workspace\proj\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node'
```

`electron-v69-win32-x64` does not exist

In my package.json I have:

```
"iohook": {
    "platforms": [
      "win32"
    ],
    "arches": [
      "x64"
    ],
    "targets": [
      "node-67",
      "electron-69"
    ]
  }
```

Any ideas?

**Comment by silvelo** [comment]
> Hi I am trying to make this work with Electron 4.2.2 but I get this error:
> 
> ```
> Uncaught Error: Cannot find module 'C:\Users\digit\Desktop\workspace\proj\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node'
> ```
> 
> `electron-v69-win32-x64` does not exist
> 
> In my package.json I have:
> 
> ```
> "iohook": {
>     "platforms": [
>       "win32"
>     ],
>     "arches": [
>       "x64"
>     ],
>     "targets": [
>       "node-67",
>       "electron-69"
>     ]
>   }
> ```
> 
> I am using whatever is current from `npm install iohook --save`
> 
> Any ideas?

For some reason only ABI 64 of electron works correctly in Windows 10.  [Check this repository](https://github.com/silvelo/electron-iohook-package)

**Comment by chipimix** [comment]
Hi!
I don't know why but iohook doesn't seem to works with electron-packager --asar option. If I don't use it it works fine, but if I do it encounter the exact same error.

**Comment by chipimix** [comment]
I ended up fixing this issue by adding the following option to electron-packager:
`--asar.unpack="**/node_modules/iohook/**"`
hope it helps!
