### ISSUE TITLE
support for electron 8?

### ISSUE THREAD

**Issue by peernohell** [wilix-team/iohook#218]
## Should support electron 8
Every thing work pefectly with electron 7.
I try to update electron to version 8, then when I npm install (after removing ./node_modules), I get this error:
```
> electron-builder install-app-deps

  • electron-builder  version=22.3.2
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=native-keymap@2.1.1, robotjs@0.6.0 platform=darwin arch=x64
  • install prebuilt binary  name=robotjs version=0.6.0 platform=darwin arch=x64
  • build native dependency from sources  name=robotjs
                                          version=0.6.0
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=/Users/peernohell/[...]/desktop/node_modules/node-abi/index.js:30
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
```

here is my iohook config in packages.json
```

  "iohook": {
    "targets": [
      "electron-75"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64"
    ]
  },
```
If I understand the error I didn't use the correct abi version, so I should update the target, but I didn't find any newer version.
## does iohook is compatible with electron 8?
So, maybe the issue is that iohook is not compatible with electron 8 or I have something to do to fix that issue. 
As I'm pretty new to electron it can be a basic issue in my configuration but as I only `ncu -u` to udpate and everything work with previous version, I'm not sure it's my fault.

## update doc?
Provide a new abi or make it more clear which abi version to use with which electron version. it will be really help full.

## Your Environment
* Version used: 0.6.4
* Environment name and version: node 12.14.1
* Operating System and version : Desktop MacOS 10.15.2

I hop you will be able to help me understand what's wrong :)
Thanks

**Comment by Djiit** [comment]
Hey! I'm working on it right now. I'll keep you posted here.

**Comment by Djiit** [comment]
Fixed in 0.6.5 ;)

**Comment by peernohell** [comment]
Seems you didn't push the new version into npm :)
on https://www.npmjs.com/package/iohook, latest version is 0.6.4

**Comment by Djiit** [comment]
Oops, done now ;)

**Comment by Seblor** [comment]
@Djiit I am trying to make iohook work with Electron 8.2.3, and running my app shows me the error 

> Cannot find module 'node_modules\iohook\builds\electron-v76-win32-x64\build\Release\iohook.node'

Even though the file exists at that location, and my config is as follows:

```js
"iohook": {
  "targets": [
    "electron-76"
  ],
  "platforms": [
    "win32",
    "darwin",
    "linux"
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
```
