### ISSUE TITLE
Error when iohook required in Main process of electron

### ISSUE THREAD

**Issue by eyesmarty** [wilix-team/iohook#308]
## Expected Behavior
should require successfully

## Current Behavior
App threw an error during load
Error: Cannot find module '/Users/*******/*******/team-viewer/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
    at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)
    at eval (webpack:///./node_modules/iohook/index.js?:10:80)
    at Object../node_modules/iohook/index.js (/Users/*******/*******/team-viewer/dist_electron/index.js:783:1)
    at __webpack_require__ (/Users/*******/*******/team-viewer/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:9:16)
    at Module../src/background.js (/Users/*******/*******/team-viewer/dist_electron/index.js:1802:1)
    at __webpack_require__ (/Users/*******/*******/team-viewer/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)

## Possible Solution
i thinks its not compatible with newer version of electron, node , mac
 "iohook": {
    "targets": [
      "node-83",
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
## Steps to Reproduce (for bugs)
create electron project with electron 11.0.0 and node version 14.14.0
install iohook
require iohook in main process 
run electron app

## Context
i am trying to get ky strocs when app is not focused but app crashes as soon as iohook is required

## Your Environment

electron 11.0.0
node :14.14.0
OS=>mac version : Catalina 10.15.6

**Comment by programerr01** [comment]
hii ,try this one 
https://github.com/wilix-team/iohook/issues/306

**Comment by marcelblum** [comment]
I'm using iohook 0.7.2 in a Mac app with Electron 11.x without problems, tests working fine on macOS 10.11-11.2. Does this error occur in a packaged app only, or in the development environment too? Does the file iohook.node actually exist in the path where it says it can't find it?

**Comment by palmerabollo** [comment]
In my case, the error shows this path:
/Users/myapp/node_modules/iohook/builds/**electron-v87**-darwin-x64/build/Release/iohook.node

And the file is actually located at:
/Users/myapp/node_modules/iohook/builds/**node-v83**-darwin-x64/build/Release/iohook.node

It's my first electron app, so I'm not sure if I'm missing something obvious.

**Comment by programerr01** [comment]
> In my case, the error shows this path:
> /Users/myapp/node_modules/iohook/builds/**electron-v87**-darwin-x64/build/Release/iohook.node
> 
> And the file is actually located at:
> /Users/myapp/node_modules/iohook/builds/**node-v83**-darwin-x64/build/Release/iohook.node
> 
> It's my first electron app, so I'm not sure if I'm missing something obvious.

actually it's the issue with electron. IoHook don't build for newer electron version that's why i switched to older version.

**Comment by sujiewen** [comment]
electron 11.3.0
node : v12.16.1
OS=>mac version : Catalina 10.15.7

iohook： 0.9.0

This error is reported when the program starts

**Comment by sujiewen** [comment]
iohook: {
    targets: [ 'node-83', 'electron-85' ],
    platforms: [ 'win32', 'darwin', 'linux' ],
    arches: [ 'x64', 'ia32' ]
  }


App threw an error during load
Error: Cannot find module '/Users/lc/st/wmswarehouse/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
    at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)

**Comment by programerr01** [comment]
> iohook: {
> targets: [ 'node-83', 'electron-85' ],
> platforms: [ 'win32', 'darwin', 'linux' ],
> arches: [ 'x64', 'ia32' ]
> }
> 
> App threw an error during load
> Error: Cannot find module '/Users/lc/st/wmswarehouse/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
> at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)

try using older version of electron.

**Comment by WilixLead** [comment]
Today I release v87 for electron. Try again with electron v12 - should work now

**Comment by palmerabollo** [comment]
@WilixLead could you please confirm if everything is ok with the new release?

> Loading native binary: /Users/xxx/electron/.webpack/main/builds/electron-v87-darwin-x64/build/Release/iohook.node
App threw an error during load
**Error: The module '/Users/xxx/electron/.webpack/main/builds/electron-v87-darwin-x64/build/Release/iohook.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88**. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing

I'm using nodejs v14.6.0, electron 12.0.2 and this is the iohook section in my package.json:

```
  "iohook": {
    "targets": [
      "electron-88"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64"
    ]
  },
```

**Comment by thamizh-qwerty** [comment]
> I'm using iohook 0.7.2 in a Mac app with Electron 11.x without problems, tests working fine on macOS 10.11-11.2. Does this error occur in a packaged app only, or in the development environment too? Does the file iohook.node actually exist in the path where it says it can't find it?

It was working in development, not in production. I resolved this after allowing permission to monitor the mouse and key events for the electron application in catalina. 

May be useful in the future.
